spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: BANDONEW
    password: BANDONEW
    driver-class-name: oracle.jdbc.OracleDriver

  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none     
    properties:
      hibernate:
        jdbc.fetch_size: 300
        jdbc.batch_size: 100
        dialect: org.hibernate.dialect.Oracle10gDialect
  
  jta:
    atomikos:
      properties:
        threaded-two-phase-commit: true
        enable-logging: false
        max-timeout: 600000

  thymeleaf:
    cache: false
    view-names: member/*

  view:
    prefix: /WEB-INF/
    suffix: .jsp
    view-names: jsp/*
    contentType: text/html; charset=utf-8
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: wooya617@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 1800

logging:
  level:
    org.springframework.web: ERROR
    hello: INFO
    
